services:
  - type: web
    name: chattrix-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    workingDir: chattrix/mysite
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
