services:
  - type: web
    name: chattrix-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.mysite.wsgi:application
    workingDir: chattrix  # Not chattrix/mysite!
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.mysite.settings
