services:
  - type: web
    name: chatrix
    env: python
    rootDir: mysite  # 👈 This is critical!
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    workingDir: mysite
    autoDeploy: true
